Repository jenkinsci/docker, pull requests merged in 2019-07, with the labels that each got.

#850 Add link to Jenkins features controlled by system properties
  README.md
Labels: documentation

#855 Add debug flags to publish-experimental.sh
  Makefile
  publish-experimental.sh
Labels: internal

#859 Experimental publishing: Add DOCKER_CONFIG echo in the path that is being used
  publish-experimental.sh
Labels: internal

#860 Jenkinsfile: Prevent CI timeout when ci.jenkins.io Docker agents are too busy
  Jenkinsfile
Labels: internal

#862 Experimental Publishing: Explicitly pass --config/--docker-cfg
  publish-experimental.sh
Labels: internal

#851 Explicitly set JAVA_HOME in the CentOS image + Add `which` package to the CentOS image
  Dockerfile-centos
Labels: enhancement

#863 Remove explicit passing of --config/--docker-cfg
  publish-experimental.sh
Labels: internal, skip-changelog

#864 Multiarch updates
  publish-experimental.sh
Labels: skip-changelog

#856 Introduce Docker Packaging changelogs
  .github/release-drafter.yml
  CHANGELOG.md
Labels: documentation

#868 Extend timeout
  Jenkinsfile
Labels: internal, skip-changelog
