Repository jenkinsci/docker, pull requests merged in 2020-01, with the labels that each got.

#890 Add OpenJ9 images for Java 1.8 and Java 11
  Dockerfile-openj9
  Dockerfile-openj9-jdk11
  Makefile
Labels: enhancement, hacktoberfest

#914 Increase Timeout
  Jenkinsfile
Labels: chore

#880 Dockerfile: add git-lfs
  Dockerfile
  Dockerfile-alpine
  Dockerfile-centos
  Dockerfile-jdk11
  Dockerfile-openj9
  Dockerfile-openj9-jdk11
  Dockerfile-slim
  multiarch/Dockerfile.alpine
  multiarch/Dockerfile.debian
  multiarch/Dockerfile.slim
Labels: enhancement

#920 Do not build containers on Wednesdays during EU daytime
  Jenkinsfile
Labels: ready-for-merge
