Repository jenkinsci/docker, pull requests merged in 2021-09, with the labels that each got.

#1201 More locale fixes
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/centos/centos7/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  8/alpine/hotspot/Dockerfile
  8/centos/centos7/hotspot/Dockerfile
  tests/runtime.bats
Labels: tests

#1202 Use Debian bullseye 2021-09-02
  11/debian/bullseye-slim/hotspot/Dockerfile
  11/debian/bullseye/hotspot/Dockerfile
  8/debian/bullseye-slim/hotspot/Dockerfile
  8/debian/bullseye/hotspot/Dockerfile
Labels: chore

#1209 Fix typo in label
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/centos/centos7/hotspot/Dockerfile
  11/debian/bullseye-slim/hotspot/Dockerfile
  11/debian/bullseye/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  11/windows/windowsservercore-2019/hotspot/Dockerfile
  8/alpine/hotspot/Dockerfile
  8/centos/centos7/hotspot/Dockerfile
  8/debian/bullseye-slim/hotspot/Dockerfile
  8/debian/bullseye/hotspot/Dockerfile
Labels: bug

#1210 Accept debug on non local connections
  jenkins.sh
Labels: bug
