Repository jenkinsci/docker, pull requests merged in 2023-10, with the labels that each got.

#1726 Use Alpine Linux 3.18.4, not 3.18.3
  11/alpine/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  21/alpine/hotspot/Dockerfile
  docker-bake.hcl
Labels: chore

#1727 chore(dependencies): Tracks Alpine Linux versions through updatecli.
  updatecli/updatecli.d/alpine.yaml
Labels: chore, alpine, updatecli

#1731 Update default Jenkins version
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/centos/centos7/hotspot/Dockerfile
  11/debian/bookworm-slim/hotspot/Dockerfile
  11/debian/bookworm/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  11/windows/windowsservercore-2019/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bookworm-slim/hotspot/Dockerfile
  17/debian/bookworm/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
  21/alpine/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/Dockerfile
  21/debian/bookworm/hotspot/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
Labels: dependencies

#1745 chore(updatecli): rename `bullseye.yaml` to `debian.yaml`
  updatecli/updatecli.d/debian.yaml
Labels: skip-changelog, chore, debian, updatecli

#1744 fix(updatecli/debian): add new jdk21 and jdk21-preview conditions and targets
  updatecli/updatecli.d/debian.yaml
Labels: skip-changelog, chore, debian, updatecli, jdk21, jdk21-preview

#1748 fixup(Jenkinsfile): add `debian_jdk21_preview` & `debian_slim_jdk21_preview`
  Jenkinsfile
Labels: skip-changelog, chore, debian, jdk21-preview

#1753 chore(jdk21-preview): don't hardcode `JAVA_MAJOR_VERSION` in release URL
  21/debian/bookworm-slim/hotspot/preview/Dockerfile
  21/debian/bookworm/hotspot/preview/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
Labels: skip-changelog, chore, debian, jdk21-preview, rhel/ubi9

#1756 fix: add additional tags for default Java images
  docker-bake.hcl
Labels: bug, alpine, debian, jdk17, debian-slim

#1757 fixup: shortest jdk17 tags only for weekly releases
  docker-bake.hcl
Labels: bug, alpine, debian, jdk17, debian-slim
