Repository jenkinsci/docker, pull requests merged in 2023-09, with the labels that each got.

#1705 Exclude Temurin major upgrades on AlmaLinux, just like others
  .github/dependabot.yml
Labels: chore

#1708 Use JDK 17.0.8.1 instead of 17.0.8
  17/alpine/hotspot/Dockerfile
  17/debian/bookworm-slim/hotspot/Dockerfile
  17/debian/bookworm/hotspot/Dockerfile
  docker-bake.hcl
Labels: chore

#1718 chore(actions): Bumps updatecli to 2.41.0.
  .github/workflows/updatecli.yaml
Labels: chore

#1710 chore(dependencies): Preliminary work to integrate `updatecli`.
  11/alpine/hotspot/Dockerfile
  11/centos/centos7/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bookworm-slim/hotspot/Dockerfile
  17/debian/bookworm/hotspot/Dockerfile
  21/alpine/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/Dockerfile
  21/debian/bookworm/hotspot/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
  docker-bake.hcl
Labels: skip-changelog

#1720 chore(dependencies): Preliminary work to integrate updatecli. Uses a JAVA_VERSION arg for Windows and RHEL 9.
  11/windows/windowsservercore-2019/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
Labels: skip-changelog

#1711 chore(dependencies): Use `updatecli` to track JDK 11, 17 and 21
  .github/dependabot.yml
  updatecli/scripts/check-jdk.sh
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
  updatecli/updatecli.d/jdk21.yaml
Labels: chore, updatecli

#1724 Java 17 by default
  HACKING.adoc
  README.md
  docker-bake.hcl
  make.ps1
Labels: chore
