Repository jenkinsci/docker, pull requests merged in 2023-05, with the labels that each got.

#1586 This patch adds ppc64le support back into the Jenkins CI Docker controller build
  Makefile
  docker-bake.hcl
Labels: enhancement

#1631 chore(Jenkinsfile) fix publication syntax error
  Jenkinsfile
Labels: chore

#1632 chore: add ksalerno as codeowner
  .github/CODEOWNERS
Labels: chore

#1633 Use JDK from UBI 9 in UBI 9 container
  17/rhel/ubi9/hotspot/Dockerfile
Labels: bug

#1634 Avoid dependabot PR's changing Alma Linux major version
  .github/dependabot.yml
Labels: chore
