Repository jenkinsci/docker, pull requests merged in 2023-11, with the labels that each got.

#1764 chore(Windows): replace hardcoded directory separator in `make.ps1`
  make.ps1
Labels: skip-changelog, chore, windows

#1767 cleanup(Windows): remove `$PushVersion` blocks from `make.ps1`
  make.ps1
Labels: skip-changelog, chore, windows

#1755 chore(Windows): log the list of tag(s) to be built
  make.ps1
Labels: skip-changelog, chore, windows

#1766 chore(Windows): add `-DryRun` option to `make.ps1` script
  make.ps1
Labels: skip-changelog, chore, windows

#1769 cleanup(Windows): remove unused `make.ps1` parameters
  make.ps1
Labels: skip-changelog, chore, windows

#1773 breaking(Windows): set Java 17 as default
  .github/dependabot.yml
  17/windows/windowsservercore-2019/hotspot/Dockerfile
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
Labels: breaking, windows, jdk17

#1777 Remove CentOS 7 container images
  .github/dependabot.yml
  11/centos/centos7/hotspot/Dockerfile
  HACKING.adoc
  Jenkinsfile
  docker-bake.hcl
Labels: breaking

#1778 Use Java 17.0.9_9
  17/alpine/hotspot/Dockerfile
  17/debian/bookworm-slim/hotspot/Dockerfile
  17/debian/bookworm/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
  17/windows/windowsservercore-2019/hotspot/Dockerfile
  docker-bake.hcl
Labels: chore

#1779 Use JDK 21.0.1+12, not 21+35
  21/alpine/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/preview/Dockerfile
  21/debian/bookworm/hotspot/Dockerfile
  21/debian/bookworm/hotspot/preview/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
Labels: chore

#1770 feat(Windows): refactor build process
  Jenkinsfile
  build-windows.yaml
  make.ps1
  tests/functions.Tests.ps1
  tests/plugins-cli.Tests.ps1
  tests/runtime.Tests.ps1
  tests/test_helpers.psm1
  windows/windowsservercore/hotspot/Dockerfile
Labels: enhancement, windows

#1782 chore(Windows): use Java 11.0.21_9
  build-windows.yaml
Labels: chore, windows, jdk11

#1784 fix(Windows): add `lts-` prefix to LTS short tags not including Jenkins version
  build-windows.yaml
  make.ps1
Labels: bug, windows

#1785 Add `JENKINS_PLUGIN_INFO` to the "Setting update centers" README section
  README.md
Labels: documentation
