Repository jenkinsci/docker, pull requests merged in 2023-01, with the labels that each got.

#1552 Add procps to Debian images for consistency with Alpine images
  11/debian/bullseye-slim/hotspot/Dockerfile
  11/debian/bullseye/hotspot/Dockerfile
  17/debian/bullseye-slim/hotspot/Dockerfile
  17/debian/bullseye/hotspot/Dockerfile
  tests/runtime.bats
Labels: bug

#1553 Use JDK 11.0.18 and JDK 17.0.6
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/centos/centos7/hotspot/Dockerfile
  11/debian/bullseye-slim/hotspot/Dockerfile
  11/debian/bullseye/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  11/windows/windowsservercore-2019/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bullseye-slim/hotspot/Dockerfile
  17/debian/bullseye/hotspot/Dockerfile
Labels: enhancement

#1554 Use ubi8:8.7 instead of ubi8:8.6
  11/rhel/ubi8/hotspot/Dockerfile
Labels: chore

#1558 workaround(publish.sh) Only check the last 3 Jenkins versions for publication
  .ci/publish.sh
Labels: chore
