Repository jenkinsci/docker, pull requests merged in 2023-06, with the labels that each got.

#1648 Download from mirrors, not repo.jenkins-ci.org
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/centos/centos7/hotspot/Dockerfile
  11/debian/bullseye-slim/hotspot/Dockerfile
  11/debian/bullseye/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  11/windows/windowsservercore-2019/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bullseye-slim/hotspot/Dockerfile
  17/debian/bullseye/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
  docker-bake.hcl
  make.ps1
  tests/test_helpers.psm1
Labels: enhancement

#1653 feat(alpine): Pin Alpine version to 3.18.0
  11/alpine/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  docker-bake.hcl
Labels: chore, alpine

#1647 Add more details to the security policy
  SECURITY.md
Labels: documentation

#1659 fix typo
  tests/test_helpers.psm1
Labels: chore
