Repository jenkinsci/docker, pull requests merged in 2023-07, with the labels that each got.

#1658 feature(dependencies): Tracks the Bullseye version thanks to updatecli
  .github/workflows/updatecli.yaml
  updatecli/updatecli.d/bullseye.yaml
  updatecli/values.github-action.yaml
Labels: chore, debian, updatecli

#1662 chore(updatecli): Fix the Debian manifest by removing the "bullseye-" prefix
  updatecli/updatecli.d/bullseye.yaml
Labels: chore, debian, updatecli

#1665 feat: :sparkles: Install tzdata for update timezone changes
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/centos/centos7/hotspot/Dockerfile
  11/debian/bullseye-slim/hotspot/Dockerfile
  11/debian/bullseye/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  17/debian/bullseye-slim/hotspot/Dockerfile
  17/debian/bullseye/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
Labels: enhancement

#1672 Download from repo.jenkins-ci.org, not get.jenkins.io
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/centos/centos7/hotspot/Dockerfile
  11/debian/bullseye-slim/hotspot/Dockerfile
  11/debian/bullseye/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  11/windows/windowsservercore-2019/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bullseye-slim/hotspot/Dockerfile
  17/debian/bullseye/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
  docker-bake.hcl
  make.ps1
  tests/test_helpers.psm1
Labels: bug

#1677 Use JDK 11.0.20 and JDK 17.0.8
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/debian/bullseye-slim/hotspot/Dockerfile
  11/debian/bullseye/hotspot/Dockerfile
  11/windows/windowsservercore-2019/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bullseye-slim/hotspot/Dockerfile
  17/debian/bullseye/hotspot/Dockerfile
  docker-bake.hcl
Labels: dependencies
