Repository jenkinsci/docker, pull requests merged in 2024-10, with the labels that each got.

#1936 fix: Adapt to recent changes in JDK download URL response
  jdk-download-url.sh
Labels: bug

#1937 Remove Java 11 support
  .ci/publish.sh
  .github/workflows/sync-plugin-manager.yml
  Jenkinsfile
  Makefile
  almalinux/almalinux8/hotspot/Dockerfile
  alpine/hotspot/Dockerfile
  build-windows-lts-with-jdk11.yaml
  debian/bookworm-slim/hotspot/Dockerfile
  debian/bookworm/hotspot/Dockerfile
  docker-bake.hcl
  make.ps1
  rhel/ubi8/hotspot/Dockerfile
  rhel/ubi9/hotspot/Dockerfile
  updatecli/scripts/check-jdk.sh
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
  updatecli/updatecli.d/jdk21.yaml
  windows/windowsservercore/hotspot/Dockerfile
Labels: breaking

#1939 Use fixed strings when searching for plugin manager version
  .github/workflows/sync-plugin-manager.yml
Labels: chore
