Repository jenkinsci/docker, pull requests merged in 2024-01, with the labels that each got.

#1804 Only run GitHub action from jenkinsci repositories
  .github/workflows/sync-plugin-manager.yml
Labels: chore

#1810 Use latest Java releases
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/debian/bookworm-slim/hotspot/Dockerfile
  11/debian/bookworm/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bookworm-slim/hotspot/Dockerfile
  17/debian/bookworm/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
  21/alpine/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/preview/Dockerfile
  21/debian/bookworm/hotspot/Dockerfile
  21/debian/bookworm/hotspot/preview/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
  build-windows.yaml
  docker-bake.hcl
  windows/windowsservercore/hotspot/Dockerfile
Labels: chore

#1814 Remove updatecli ref to non-existent file
  updatecli/updatecli.d/jdk17.yaml
Labels: chore

#1809 Only run actions from jenkinsci org
  .github/workflows/release-drafter.yml
  .github/workflows/updatecli.yaml
Labels: chore

#1816 Use Alpine 3.19.1, no 3.18.4 for Java 17 container default
  17/alpine/hotspot/Dockerfile
Labels: chore

#1817 Remove install-plugins.sh from ubi9 Java 17 and Java 21
  17/rhel/ubi9/hotspot/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
Labels: bug

#1818 Use consistent jlink args within Java versions
  11/alpine/hotspot/Dockerfile
  11/debian/bookworm-slim/hotspot/Dockerfile
  11/debian/bookworm/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bookworm-slim/hotspot/Dockerfile
  17/debian/bookworm/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
  21/alpine/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/Dockerfile
  21/debian/bookworm/hotspot/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
Labels: chore

#1819 Reduce diffs between similar files
  11/alpine/hotspot/Dockerfile
  11/debian/bookworm-slim/hotspot/Dockerfile
  11/debian/bookworm/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bookworm-slim/hotspot/Dockerfile
  17/debian/bookworm/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
  21/alpine/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/Dockerfile
  21/debian/bookworm/hotspot/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
Labels: chore

#1820 Add Java 21 Windows container
  build-windows.yaml
  tests/functions.Tests.ps1
  tests/plugins-cli.Tests.ps1
  tests/runtime.Tests.ps1
Labels: enhancement

#1821 Use Jenkins 2.442 as default version
  11/almalinux/almalinux8/hotspot/Dockerfile
  11/alpine/hotspot/Dockerfile
  11/debian/bookworm-slim/hotspot/Dockerfile
  11/debian/bookworm/hotspot/Dockerfile
  11/rhel/ubi8/hotspot/Dockerfile
  17/alpine/hotspot/Dockerfile
  17/debian/bookworm-slim/hotspot/Dockerfile
  17/debian/bookworm/hotspot/Dockerfile
  17/rhel/ubi9/hotspot/Dockerfile
  21/alpine/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/Dockerfile
  21/debian/bookworm-slim/hotspot/preview/Dockerfile
  21/debian/bookworm/hotspot/Dockerfile
  21/debian/bookworm/hotspot/preview/Dockerfile
  21/rhel/ubi9/hotspot/Dockerfile
  make.ps1
  windows/windowsservercore/hotspot/Dockerfile
Labels: chore

#1823 Remove ppc64le jdk21-preview images, add jdk21 images
  docker-bake.hcl
Labels: enhancement
