Repository jenkinsci/docker, pull requests merged in 2025-05, with the labels that each got.

#2008 Use JDK 21 as default JDK instead of JDK 17
  build-windows.yaml
  docker-bake.hcl
Labels: enhancement, breaking

#900 PRE_CLEAR_INIT_GROOVY_D: Add in ability to pre-clear the init.groovy.d folder
  README.md
  jenkins.sh
Labels: enhancement

#2019 Use CODEOWNERS instead of dependabot reviewers
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: internal

#2022 Use 2.504 as default base version
  Makefile
  alpine/hotspot/Dockerfile
  debian/bookworm-slim/hotspot/Dockerfile
  debian/bookworm/hotspot/Dockerfile
  docker-bake.hcl
  make.ps1
  rhel/ubi9/hotspot/Dockerfile
  windows/windowsservercore/hotspot/Dockerfile
Labels: internal

#2023 chore: Use the Junit output format of bats
  Makefile
Labels: tests, chore
